{% set version = "2.2.1" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: 6ce4747423fe2dde55bbdf89f0c3dc68044176d16d5f6a2cfbfe6c68b99db405

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pymeeus <=1,>=0.3.6
    - pytz >=2014.10


test:
  imports:
    - convertdate
    - convertdate.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_file: LICENSE
  summary: "Converts between Gregorian dates and other calendar systems.Calendars included: Baha'i, French Republican, Hebrew, Indian Civil, Islamic, ISO, Julian, Mayan and Persian."

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
