{% set version = "2.2.1" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: 6ce4747423fe2dde55bbdf89f0c3dc68044176d16d5f6a2cfbfe6c68b99db405

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ephem >=3.7.5.3,<3.8
    - pytz >=2014.10,<2020

test:
  imports:
    - convertdate
    - convertdate.data

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_file: LICENSE
  summary: Converts between Gregorian dates and other calendar systems

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
