{% set version = "2.4.1" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: ace904a9d0230742732471748160b99d6ae881c2d0dc9a2463c7a37340c56c91

build:
  skip: true  # [py<37]
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools >=61.1.1
    - wheel
  run:
    - python
    - pymeeus >=0.3.13,<=1
    - pytz >=2014.10

test:
  imports:
    - convertdate
    - convertdate.data
  commands:
    - pip check
  requires:
    # due to bug in conda build which causes python 3.10 to be used
    - python <3.10
    - pip

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Converts between Gregorian dates and other calendar systems.Calendars included: Baha'i, French Republican, Hebrew, Indian Civil, Islamic, ISO, Julian, Mayan and Persian."
  dev_url: https://github.com/fitnr/convertdate
  doc_url: https://convertdate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
