{% set version = "2.1.3" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: c3ca5ba66b31e29d2732bdb361422ed804d3b22c115659d05a43d1fc527b9773
  patches:
    - win_charmap.patch  # [win and py>27]

build:
  number: 1000
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ephem
    - pytz

test:
  imports:
    - convertdate
    - convertdate.data

about:
  home: https://github.com/scrapinghub/convertdate
  license: MIT
  license_file: LICENSE
  summary: 'Converts between Gregorian dates and other calendar systems.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
