{% set name = "convertdate" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ace904a9d0230742732471748160b99d6ae881c2d0dc9a2463c7a37340c56c91

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.1.1
    - wheel
  run:
    - python
    - pymeeus >=0.3.13,<=1

# Test setup missing in GH and PyPi
test:
  imports:
    - convertdate
    - convertdate.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Converts between Gregorian dates and other calendar systems.Calendars included: Baha'i, French Republican, Hebrew, Indian Civil, Islamic, ISO, Julian, Mayan and Persian."
  dev_url: https://github.com/fitnr/convertdate
  doc_url: https://convertdate.readthedocs.io

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
