# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "A/Ubj/l/4rn4WQTphnLe+IT3ixXh51C0jT1XZJALGN2+G2kABGCEQTY+OxF0hTd94h6ARMRd2FZZ7rDLKsz5BHIjrvfzNcgvNCvJqMcFijynJZ7bAZpzLB3z7zBK8cR/nPqT7FO1fviuqlMsFdwkxs7C7igyxVcyduasuuGf7wtWVbYD4rdjZo51El9F+UzB/GdUHMGZbdvjr1v/5h6KuHvovMSF7wT7od5UNsFGk1OxNi7N0qrlLTbA7xvED7PSzliodM7UmRnGqMyEssGtV9GjSPKWxJbWagMWigjjSRh6CROKhGJ80BFC28adiBXwlVhwPtjShZ6eyhttUiGAaQ7aGi72jvJmtGfGuvcTyWF5ehbsNxSFHEormo4al9IBr0Qlxpqwz95SyxPz8yboq8GeLTzx7FTwnuqGORoM4zvfI5DvIk94mLaCUp7JfLlW32mNWB0JMDr4htBjywgSWs76kQP3naL6Rb6vCv1GkyJczkfPPJjd2zkRyLzKeH2eVot/VEZErDFeqMT7dt2fZsNE2YDocy2fCS608GufC/Kxoq/UXuINAaqpVRLPhJI7YptbSYcC6ttII5maEjJp4eHnwgWQR7BxLrLwnd1JzLshCCxEdf37JeSedUTo/UiCaRUosOJAlhXXTwPZpP5mDwX7oTbWoNwG/MjKkJDMH5U="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
