travis:
  secure:
    BINSTAR_TOKEN: K+FDI6kYT0+xxMZiTBG4toBJ3dy8fnXL0tSBVpK3AG3Uv0ue48bxJzVj4uuNQQ/cd8X7jTzdFFFp043Q948V95grvJYNMF1Rx7aSaF8Bcqj9urcbA9chhK+1effDlnfuY2VEm4hLhvBWAW0/hoJpTYH8DurM0ScHvFEKcuEK62fYJZFiHtp+zrQwTbvNoJkkVQFzXouBhFmeEnwhpHNs5WCailpqY4avUsToOBjDNGW/GyXQN11FtBqjIBRAPW5zkhYICGwsHCSWhNV27k80dDvxD0a3hMVq75gyREkinauBS2/ksdHfhMJoYZ1AiU2BL9i5q7jPxXA0qHpeZcHr4zFycc8INjBDBON/JGxdMqg96pFSsw7DJ/Si7eU+c1J8fXfHAvHfgLP9hd38FdKjD+TOTODRLXgGx2pk/B71XH+krFTimY2iG9JTZePp9YMbt48hv0tXBO5bivOJMf6NYbfZbQylfcfamMuzC2yuNigGXB/CJQzTeIIjNZWMBL/bWEUCTVpNgjqQblDCHDj7mUEbEIfXHKXqh4OQxIDu8mecSr4UB7Wbzkxpe/BOG8Lf/jqPHAS5XxNdHWvj4GIz/uhAzNIjSkX8q8//lKvO8gdpKofW2xuyYnwCUyXEC5fmoNCQcwkgU2Gv2ssRgF1rtUIiUZ4eLtmhGJS259K2pVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
