travis:
  secure:
    BINSTAR_TOKEN: A/Ubj/l/4rn4WQTphnLe+IT3ixXh51C0jT1XZJALGN2+G2kABGCEQTY+OxF0hTd94h6ARMRd2FZZ7rDLKsz5BHIjrvfzNcgvNCvJqMcFijynJZ7bAZpzLB3z7zBK8cR/nPqT7FO1fviuqlMsFdwkxs7C7igyxVcyduasuuGf7wtWVbYD4rdjZo51El9F+UzB/GdUHMGZbdvjr1v/5h6KuHvovMSF7wT7od5UNsFGk1OxNi7N0qrlLTbA7xvED7PSzliodM7UmRnGqMyEssGtV9GjSPKWxJbWagMWigjjSRh6CROKhGJ80BFC28adiBXwlVhwPtjShZ6eyhttUiGAaQ7aGi72jvJmtGfGuvcTyWF5ehbsNxSFHEormo4al9IBr0Qlxpqwz95SyxPz8yboq8GeLTzx7FTwnuqGORoM4zvfI5DvIk94mLaCUp7JfLlW32mNWB0JMDr4htBjywgSWs76kQP3naL6Rb6vCv1GkyJczkfPPJjd2zkRyLzKeH2eVot/VEZErDFeqMT7dt2fZsNE2YDocy2fCS608GufC/Kxoq/UXuINAaqpVRLPhJI7YptbSYcC6ttII5maEjJp4eHnwgWQR7BxLrLwnd1JzLshCCxEdf37JeSedUTo/UiCaRUosOJAlhXXTwPZpP5mDwX7oTbWoNwG/MjKkJDMH5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
