travis:
  secure:
    BINSTAR_TOKEN: redoqg6OkNP3rrtuM+4xbwTce66Xml41KF7tNSAlpVi5XshXydKhwahgg9Qz9S8f6fySCGLBtvM91NLBH5iLYNFoIhkvuRz7bA+xzlS5v0Kr5VfgTgjPCEZzthVSJRFUBsWzZiTWmy5zgT281HMfxt6QFcAuAC1n4SB2KV4wFu+hnoAe/M4Uvci88RKC3/Z6NX3XuD+xDbX+ILVnY6uEwJBh7A+wRVMSdym9jxwnh6plm7kqxyoutG7aJUJ4C6pq2ocfWNMUZx5lgH6526p4jnZzGOtu/cPn4T1zJG/KNneQPfBLhKxWJueQvmzcpKjne9EZWKhqD044nLLcWlsi26v8T0AByNe3qm0yE/MWK9a8gUKf6KbMjnVybOI5jw26vYbEXGgmF4Mv5e5FJjRApodQZxPBjpiuXWJBiYVBVSgcmcu9zWU5iiCpqbZKU5JolKdJPhNJLyY6pV0rNA0j7glcZwxW8NyepebjmtSbO8udCo0xf/TwxTbIRwjcbx2WyhEjcdOt9mdxnRIKcmDYKA4p27i94XuRfkXTRet4LJ4nYBnlws3nG98dITlz4S3Cx3BulgK3EmjtXe4Fmk0KYv1GdWNQQPxRNL9wvWLW2XqExLY6CKpLxE7qpHOX3DLKBceLirWFYY1WTH0Ok3oU+AehQuu4z1oFCVb6eOKHxE4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
